@Entity
public class ParticipantDemandCorrectionAttachmentEntity extends BaseAttachmentKeyEntity<ParticipantDemandCorrectionAttachmentKey> {

    private ParticipantDemandCorrectionEntity participantDemandCorrection;
}
